import {
  FaMobileAlt,
  FaLaptop,
  FaHeadphones,
  FaCamera,
  FaTabletAlt,
  FaTv,
  FaGamepad,
  FaDesktop,
  FaNetworkWired,
  FaMicrophone,
  FaMemory,
  FaKeyboard,
  FaChargingStation,
  FaBatteryFull,
  FaSpeakerDeck,
  FaUsb,
  FaBluetooth,
  FaRobot,
  FaCameraRetro,
  FaVideo,
  FaLightbulb,
  FaPlug,
  FaBroadcastTower,
  FaCompactDisc,
  FaHdd,
} from "react-icons/fa";

export const iconOptions = [
  { label: "Mobile", value: "mobile", icon: FaMobileAlt },
  { label: "Laptop", value: "laptop", icon: FaLaptop },
  { label: "Headphones", value: "headphones", icon: FaHeadphones },
  { label: "Camera", value: "camera", icon: FaCamera },
  { label: "Tablet", value: "tablet", icon: FaTabletAlt },
  { label: "Television", value: "television", icon: FaTv },
  { label: "Gaming", value: "gaming", icon: FaGamepad },
  { label: "Desktop PC", value: "desktop", icon: FaDesktop },
  { label: "Networking", value: "networking", icon: FaNetworkWired },
  { label: "Microphone", value: "microphone", icon: FaMicrophone },
  { label: "RAM", value: "ram", icon: FaMemory },
  { label: "Keyboard", value: "keyboard", icon: FaKeyboard },
  { label: "Chargers", value: "charger", icon: FaChargingStation },
  { label: "Battery", value: "battery", icon: FaBatteryFull },
  { label: "Speakers", value: "speakers", icon: FaSpeakerDeck },
  { label: "USB Devices", value: "usb", icon: FaUsb },
  { label: "Bluetooth", value: "bluetooth", icon: FaBluetooth },
  { label: "Robotics", value: "robotics", icon: FaRobot },

  // Additional categories
  { label: "Vintage Camera", value: "vintage-camera", icon: FaCameraRetro },
  { label: "Video Equipment", value: "video-equipment", icon: FaVideo },
  { label: "Smart Lighting", value: "smart-lighting", icon: FaLightbulb },
  { label: "Power Plug", value: "power-plug", icon: FaPlug },
  { label: "Broadcasting", value: "broadcasting", icon: FaBroadcastTower },
  { label: "Storage", value: "storage", icon: FaCompactDisc },
  { label: "Hard Drives", value: "hard-drive", icon: FaHdd },
];
